#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
    path: /logout
    methods: GET
admin/contentTab3:
    path: 'admin/#contentTab3'
    controller: App\Controller\AdminController::index